### ISSUE TITLE
Can you modify this to generate images for unseen patterns ? 

### ISSUE THREAD

**Issue by shamanez** [sebasvega95/neural-style-transfer#2]
https://pdfs.semanticscholar.org/ee3e/953fc9cad23f7eab0e1f6570c8033d8e2e57.pdf

**Comment by sebasvega95** [comment]
I haven't look at that paper before. If they claim that you can take [Johnson et al's model](https://arxiv.org/abs/1603.08155) and extend it, then you could try it by starting from this code.
