### ISSUE TITLE
can you please upload tensor-board visualisations of your own  training ?

### ISSUE THREAD

**Issue by shamanez** [sebasvega95/neural-style-transfer#4]
Actually, algorithm got converged. I added a slight modification that is to concatenate style image features before the residual block. But the Content loss is huge. So I think it will be useful for users to check whether their loss scale is normal or not.

**Comment by sebasvega95** [comment]
The logs directory [gets erased every run](https://github.com/sebasvega95/neural-style-transfer/blob/master/train.py#L78), so I don't have them 😅 I used the Tensorboard visualizations to check if both content and style losses where descending steadily with a choice of loss weights.

I don't really know what the modification you did involve, you might try fiddling with these loss weights values if you find one of the losses isn't descending.
